# png2lvgl.ps1 — convert a PNG to an LVGL 8.x C image descriptor
# (LV_IMG_CF_TRUE_COLOR_ALPHA, RGB565 little-endian + 8-bit alpha, LV_COLOR_16_SWAP 0).
#
# A solid magenta (#FF00FF-ish) background is treated as transparent, including
# the purple anti-aliasing fringe left along dark outlines.
#
# Usage:
#   powershell -File tools/png2lvgl.ps1 -In icon.png -Out icon.c -Name my_icon -TargetHeight 100

param(
  [Parameter(Mandatory=$true)][string]$In,
  [Parameter(Mandatory=$true)][string]$Out,
  [Parameter(Mandatory=$true)][string]$Name,
  [int]$TargetHeight = 100
)

Add-Type -AssemblyName System.Drawing

$srcFile = [System.Drawing.Bitmap]::new((Resolve-Path $In).Path)
# Force 32bpp: on a 24bpp source, UnlockBits would silently discard the alpha
# written during chroma-keying.
$src = $srcFile.Clone([System.Drawing.Rectangle]::new(0, 0, $srcFile.Width, $srcFile.Height),
                      [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$srcFile.Dispose()

# --- Pass 1: chroma-key magenta at full resolution ---
$rect = [System.Drawing.Rectangle]::new(0, 0, $src.Width, $src.Height)
$data = $src.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadWrite,
                      [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$bytes = New-Object byte[] ($data.Stride * $src.Height)
[System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)

$minX = $src.Width; $minY = $src.Height; $maxX = 0; $maxY = 0
for ($y = 0; $y -lt $src.Height; $y++) {
  $row = $y * $data.Stride
  for ($x = 0; $x -lt $src.Width; $x++) {
    $i = $row + $x * 4
    $b = $bytes[$i]; $g = $bytes[$i+1]; $r = $bytes[$i+2]
    $isMagenta = ($r -gt 180 -and $b -gt 180 -and $g -lt 120)
    $isFringe  = ($r -gt 100 -and $b -gt 100 -and $g -lt ($r * 0.6) -and $g -lt ($b * 0.6))
    if ($isMagenta -or $isFringe) {
      $bytes[$i+3] = 0
    } else {
      if ($x -lt $minX) { $minX = $x }; if ($x -gt $maxX) { $maxX = $x }
      if ($y -lt $minY) { $minY = $y }; if ($y -gt $maxY) { $maxY = $y }
    }
  }
}
[System.Runtime.InteropServices.Marshal]::Copy($bytes, 0, $data.Scan0, $bytes.Length)
$src.UnlockBits($data)

# --- Pass 2: crop to content, scale to target height ---
$cw = $maxX - $minX + 1; $ch = $maxY - $minY + 1
$outH = $TargetHeight
$outW = [int][Math]::Round($cw * $outH / $ch)
$dst = [System.Drawing.Bitmap]::new($outW, $outH, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$gfx = [System.Drawing.Graphics]::FromImage($dst)
$gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$gfx.DrawImage($src, [System.Drawing.Rectangle]::new(0, 0, $outW, $outH),
               $minX, $minY, $cw, $ch, [System.Drawing.GraphicsUnit]::Pixel)
$gfx.Dispose()

# --- Pass 3: emit the C array ---
$rect2 = [System.Drawing.Rectangle]::new(0, 0, $outW, $outH)
$data2 = $dst.LockBits($rect2, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                       [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$px = New-Object byte[] ($data2.Stride * $outH)
[System.Runtime.InteropServices.Marshal]::Copy($data2.Scan0, $px, 0, $px.Length)
$dst.UnlockBits($data2)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Generated by tools/png2lvgl.ps1 from $(Split-Path $In -Leaf) ($outW x $outH)")
[void]$sb.AppendLine("// Format: LV_IMG_CF_TRUE_COLOR_ALPHA (RGB565 LE + alpha, LV_COLOR_16_SWAP 0)")
[void]$sb.AppendLine('#ifndef LV_LVGL_H_INCLUDE_SIMPLE')
[void]$sb.AppendLine('#define LV_LVGL_H_INCLUDE_SIMPLE')
[void]$sb.AppendLine('#endif')
[void]$sb.AppendLine('#include "lvgl.h"')
[void]$sb.AppendLine('#ifndef LV_ATTRIBUTE_MEM_ALIGN')
[void]$sb.AppendLine('#define LV_ATTRIBUTE_MEM_ALIGN')
[void]$sb.AppendLine('#endif')
[void]$sb.AppendLine("static const LV_ATTRIBUTE_MEM_ALIGN uint8_t ${Name}_map[] = {")

$line = [System.Text.StringBuilder]::new()
for ($y = 0; $y -lt $outH; $y++) {
  $row = $y * $data2.Stride
  for ($x = 0; $x -lt $outW; $x++) {
    $i = $row + $x * 4
    $b = $px[$i]; $g = $px[$i+1]; $r = $px[$i+2]; $a = $px[$i+3]
    $v = (($r -shr 3) -shl 11) -bor (($g -shr 2) -shl 5) -bor ($b -shr 3)
    [void]$line.AppendFormat("0x{0:x2},0x{1:x2},0x{2:x2},", ($v -band 0xFF), ($v -shr 8), $a)
    if ((($y * $outW + $x) % 12) -eq 11) {
      [void]$sb.AppendLine($line.ToString()); [void]$line.Clear()
    }
  }
}
if ($line.Length -gt 0) { [void]$sb.AppendLine($line.ToString()) }

[void]$sb.AppendLine('};')
[void]$sb.AppendLine("const lv_img_dsc_t $Name = {")
[void]$sb.AppendLine('  .header.always_zero = 0,')
[void]$sb.AppendLine("  .header.w = $outW,")
[void]$sb.AppendLine("  .header.h = $outH,")
[void]$sb.AppendLine('  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
[void]$sb.AppendLine("  .data_size = $outW * $outH * 3,")
[void]$sb.AppendLine("  .data = ${Name}_map,")
[void]$sb.AppendLine('};')

Set-Content -Path $Out -Value $sb.ToString() -Encoding ascii
$src.Dispose(); $dst.Dispose()
Write-Host "Wrote $Out ($outW x $outH, $($outW * $outH * 3) bytes)"
